# Aula 02 - Pandas 
## Analise de um dataset de compras de um e - commerce

In [5]:
import pandas as pd

# Criar um dataframe
df = pd.read_csv('Ecommerce Purchases.csv')

# Ver apenas as primeiras linhas
display(df.head())

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [7]:
# Imprimi as colunas
# print(df.columns)

for i in df.columns:
    print(i)

Address
Lot
AM or PM
Browser Info
Company
Credit Card
CC Exp Date
CC Security Code
CC Provider
Email
Job
IP Address
Language
Purchase Price

In [16]:
# Ver apenas uma coluna
print(df['Language'].head(2))

print('\n------------------------------------------\n')

# Ver mais que uma coluna
print(df[['Company','Language','CC Provider']].head(2))

0    el
1    fr
Name: Language, dtype: object

------------------------------------------

                           Company Language   CC Provider
0                  Martinez-Herman       el  JCB 16 digit
1  Fletcher, Richards and Whitaker       fr    Mastercard

In [19]:
# Agrupar as vendas por idioma
idioma = df.groupby('Language')['Language'].count()
print(idioma)

job = df.groupby('Job')['Job'].count()
print(job)

Language
de    1155
el    1137
en    1098
es    1095
fr    1097
it    1086
pt    1118
ru    1155
zh    1059
Name: Language, dtype: int64
Job
Academic librarian                  11
Accommodation manager               17
Accountant, chartered               20
Accountant, chartered certified     18
Accountant, chartered management    15
                                    ..
Water quality scientist             18
Web designer                        20
Wellsite geologist                  24
Writer                              10
Youth worker                        18
Name: Job, Length: 623, dtype: int64

In [ ]:
# Somar uma coluna
total = df["Purchase Price"].sum()

print(f'Faturamento de vendas : $ {total:.2f} dólares')

# Vendas por tipo de cartão usado
vendasCartao = df.groupby('CC Provider')['Purchase Price' ].sum()
print(vendasCartao)

print('\n-----------------------------------------\n')

# Apresente a média de vendas por idioma (mean)
mediaCartao = df.groupby('Language')['Purchase Price'].mean()
print(mediaCartao)

Faturamento de vendas : $ 503473.02 dólares
CC Provider
American Express               42865.52
Diners Club / Carte Blanche    37378.39
Discover                       42208.13
JCB 15 digit                   44376.60
JCB 16 digit                   84597.33
Maestro                        42620.78
Mastercard                     40835.10
VISA 13 digit                  39976.54
VISA 16 digit                  85528.86
Voyager                        43085.77
Name: Purchase Price, dtype: float64

-----------------------------------------

Language
de    50.254485
el    51.555356
en    51.103015
es    49.366977
fr    49.476718
it    50.001004
pt    51.215546
ru    49.927134
zh    50.180198
Name: Purchase Price, dtype: float64

In [34]:
# Criar filtros

# Ver apenas as vendas de um idioma especifico

idioma_el = df[df['Language'] =='el']
display(idioma_el[['Job','Language']].head(10))

                                       Job Language
0   Scientist, product/process development       el
10           Development worker, community       el
15                          Retail manager       el
17                     Designer, jewellery       el
18                            Photographer       el
39                       Minerals surveyor       el
43                      Purchasing manager       el
56           Clothing/textile technologist       el
58                 Housing manager/officer       el
61                           Buyer, retail       el

In [ ]:
# Criar duas colunas
# Coluna 1 - Imposto de 10% sobre as vendas 
df['imposto'] = df['Purchase Price'] * 0.10

display(df[['Purchase Price','imposto']])
# Coluna 2 - Calcular o valor da venda - o imposto 
# ValorSemImposto

df['ValorSemImposto'] = df['Purchase Price'] - df['imposto'] 

display(df[['Purchase Price','imposto','ValorSemImposto']])

      Purchase Price  imposto
0              98.14    9.814
1              70.73    7.073
2               0.95    0.095
3              78.04    7.804
4              77.82    7.782
...              ...      ...
9995           82.21    8.221
9996           25.63    2.563
9997           83.98    8.398
9998           38.84    3.884
9999           67.59    6.759

[10000 rows x 2 columns]

      Purchase Price  imposto  ValorSemImposto
0              98.14    9.814           88.326
1              70.73    7.073           63.657
2               0.95    0.095            0.855
3              78.04    7.804           70.236
4              77.82    7.782           70.038
...              ...      ...              ...
9995           82.21    8.221           73.989
9996           25.63    2.563           23.067
9997           83.98    8.398           75.582
9998           38.84    3.884           34.956
9999           67.59    6.759           60.831

[10000 rows x 3 columns]